### PR TITLE
Update uthmani

### PR DESCRIPTION
**Pull request by islam2hamy**
#16

please add files "quran-uthmani" to download url "https://raw.githubusercontent.com/mirfatif/NoorUlHuda/data/databases/"

### CODE REVIEW

**Comment by mirfatif** [comment]
It's WIP. Some characters in Uthmani text will look distorted with current fonts. There are some changes needed in the app before we can add Uthmani text.

https://t.me/NoorUlHudaApp/352
https://t.me/NoorUlHudaApp/387
https://t.me/NoorUlHudaApp/758

**Comment by islam2hamy** [comment]
What about update the font ?

https://fonts.qurancomplex.gov.sa/wp02/حفص/#05

**Comment by islam2hamy** [comment]
Let me help to get it work

**Comment by islam2hamy** [comment]
Or use KFGQPC hafs font

https://tanzil.net/docs/quranic_fonts

**Pull request closed without merging**
